---
  - name: epel-release 설치
    action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

  - name: mariadb 설치
    action: "{{ ansible_pkg_mgr }} name=mariadb-server state=present"

  - name: python mysql 라이브러리 설치
    action: "{{ ansible_pkg_mgr }} name=MySQL-python state=latest"

  - name: my.cnf file 복사
    template:
        src=my.cnf.j2 dest=/etc/my.cnf mode=0600
        #my.cnf.j2파일을 /etc/my.cnf에 적용, root 읽기 쓰기 권한

  - name: mysql server 시작
    action: service name=mariadb state=started enabled=true

  - name: mysql root password 업데이트
    mysql_user:
        login_user: root
        login_password: "{{ mysql.root_password }}"
        name: root
        host: "{{ item }}"
        password: "{{ mysql.root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
        #권한설정(모든 db 및 테이블에 접근권한 부여)

    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

  - name: test db 삭제
    mysql_db:
        login_user: root
        login_password: "{{ mysql.root_password }}"
        db: test
        state: absent

  - name: 새로운 db 생성
    mysql_db:
        login_user: root
        login_password: "{{ mysql.root_password }}"
        name: "{{ mysql.user_db_name }}"
        collation: "{{ mysql.collation }}"
        encoding: "{{ mysql.encoding }}"
        state: present

  - name: anonymouse user 삭제
    mysql_user:
        login_user: root
        login_password: "{{ mysql.root_password }}"
        name: ""
        host_all: yes
        state: absent

  - name: new user 생성
    mysql_user:
        login_user: root
        login_password: "{{ mysql.root_password }}"
        name: "{{ mysql.user }}"
        password: "{{ mysql.user_password }}"
        priv: "{{ mysql.user_db_name }}.*:ALL,GRANT"
        host: "%"
        state: present