---
  - name: epel-release 설치
    action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
  - name: nginx web server 설치
    action: "{{ ansible_pkg_mgr }} name=nginx state=present"
  - name: nginx.conf file 복사
    action: template src=../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
        - nginx web server 재시작