---
# handlers for nginx
- name: nginx web server 시작
  action: service name=nginx state=started
- name: nginx web server 재시작
  action: service name=nginx state=restarted
# handlers for php
- name: php 재시작
  action: service name=php-fpm state=restarted