---
- name: 앤서블 서버 환경 
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Add "/ect/ansible/hosts"
      blockinfile:
        path: /etc/ansible/hosts
        block: |
            [webservers]
            #주소를 적으시오