# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #클라이언트 서버
  config.vm.define "ansible-client" do |web|
      web.vm.box = "centos/7"
      web.vm.provider "virtualbox" do |vb|
          vb.name = "ansible-client"
      end
      web.vm.host_name = "ansible-client"
      web.vm.network "public_network", ip: "주소 적기"
      web.vm.network "forwarded_port", guest: 22, host: 원하는 포트, auto_correct: true, id: "ssh" 
      web.vm.network "forwarded_port", guest: 80, host: 원하는 포트, auto_correct: true
      #ssh,http 포트포워딩 
      web.vm.synced_folder "../shared_data", "/shared_data", disabled: true
      web.vm.provision "shell", path: "password_setting_change.sh"
      #프로비저닝 - config파일 설정 쉘 스크립트
  end

 

  #앤서블 서버
  config.vm.define "ansible-server" do |ans|
      ans.vm.box = "centos/7"
      ans.vm.provider "virtualbox" do |vb|
          vb.name="ansible-server"
      end
      ans.vm.host_name = "ansible-server"
      ans.vm.network "public_network", ip: "주소 적기"
      ans.vm.network "forwarded_port", guest: 22, host: 원하는 포트, auto_correct: true, id: "ssh"
      ans.vm.network "forwarded_port", guest: 80, host: 원하는 포트, auto_correct: true
      #ssh,http 포트포워딩
      ans.vm.synced_folder "../shared_data", "/shared_data", disabled: true
      ans.vm.provision "shell", inline: "yum install epel-release -y"
      ans.vm.provision "shell", inline: "yum install ansible -y"
      ans.vm.provision "shell", inline: "yum install tree -y"
      # 프로비저닝 - epel 저장소 추가, 앤서블 설치, 트리 설치
      ans.vm.provision "file", source: "ansible-env.yml", destination: "ansible-env.yml"
      ans.vm.provision "shell", inline: "ansible-playbook ansible-env.yml"
      ans.vm.provision "file", source: "auto_ssh_connect.yml", destination: "auto_ssh_connect.yml"
      ans.vm.provision "shell", inline: "ansible-playbook auto_ssh_connect.yml", privileged: false
      # 프로비저닝 - ansible 환경설정, ssh 설정
  end
end